var searchData=
[
  ['calibration_20apis',['Calibration APIs',['../group__calib__group.html',1,'']]],
  ['core_20definitions',['Core Definitions',['../group___c_m_s_i_s__core__base.html',1,'']]],
  ['cmsis_20core_20instruction_20interface',['CMSIS Core Instruction Interface',['../group___c_m_s_i_s___core___instruction_interface.html',1,'']]],
  ['cmsis_20core_20register_20access_20functions',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['core_20debug_20registers_20_28coredebug_29',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]],
  ['cmsis_20global_20defines',['CMSIS Global Defines',['../group___c_m_s_i_s__glob__defs.html',1,'']]],
  ['crdelay',['crDELAY',['../group__cr_d_e_l_a_y.html',1,'']]],
  ['crqueue_5freceive',['crQUEUE_RECEIVE',['../group__cr_q_u_e_u_e___r_e_c_e_i_v_e.html',1,'']]],
  ['crqueue_5freceive_5ffrom_5fisr',['crQUEUE_RECEIVE_FROM_ISR',['../group__cr_q_u_e_u_e___r_e_c_e_i_v_e___f_r_o_m___i_s_r.html',1,'']]],
  ['crqueue_5fsend',['crQUEUE_SEND',['../group__cr_q_u_e_u_e___s_e_n_d.html',1,'']]],
  ['crqueue_5fsend_5ffrom_5fisr',['crQUEUE_SEND_FROM_ISR',['../group__cr_q_u_e_u_e___s_e_n_d___f_r_o_m___i_s_r.html',1,'']]],
  ['crstart',['crSTART',['../group__cr_s_t_a_r_t.html',1,'']]],
  ['connecting_20procedure_20apis',['Connecting Procedure APIs',['../group__gap__conn__group.html',1,'']]],
  ['compiler_20abstraction_20layer_20and_20code_20utilities',['Compiler abstraction layer and code utilities',['../group__group__sam0__utils.html',1,'']]],
  ['complex_20math_20functions',['Complex Math Functions',['../group__group_cmplx_math.html',1,'']]],
  ['controller_20functions',['Controller Functions',['../group__group_controller.html',1,'']]],
  ['cortex_2dm0_2b_20micro_2dtrace_20buffer',['Cortex-M0+ Micro-Trace Buffer',['../group___s_a_m_d21___m_t_b.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_e15_a__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_e15_b__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_e15_b_u__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_e15_l__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_e16_a__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_e16_b__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_e16_b_u__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_e16_l__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_e17_a__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_e18_a__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_g15_a__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_g15_b__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_g15_l__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_g16_a__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_g16_b__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_g16_l__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_g17_a__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_g17_a_u__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_g18_a__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_g18_a_u__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_j15_a__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_j15_b__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_j16_a__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_j16_b__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_j17_a__cmsis.html',1,'']]],
  ['cmsis_20definitions',['CMSIS Definitions',['../group___s_a_m_d21_j18_a__cmsis.html',1,'']]]
];
