var group___s_a_m_d21__definitions =
[
    [ "SAMD21E15A definitions", "group___s_a_m_d21_e15_a__definitions.html", "group___s_a_m_d21_e15_a__definitions" ],
    [ "SAMD21E15B definitions", "group___s_a_m_d21_e15_b__definitions.html", "group___s_a_m_d21_e15_b__definitions" ],
    [ "SAMD21E15BU definitions", "group___s_a_m_d21_e15_b_u__definitions.html", "group___s_a_m_d21_e15_b_u__definitions" ],
    [ "SAMD21E15L definitions", "group___s_a_m_d21_e15_l__definitions.html", "group___s_a_m_d21_e15_l__definitions" ],
    [ "SAMD21E16A definitions", "group___s_a_m_d21_e16_a__definitions.html", "group___s_a_m_d21_e16_a__definitions" ],
    [ "SAMD21E16B definitions", "group___s_a_m_d21_e16_b__definitions.html", "group___s_a_m_d21_e16_b__definitions" ],
    [ "SAMD21E16BU definitions", "group___s_a_m_d21_e16_b_u__definitions.html", "group___s_a_m_d21_e16_b_u__definitions" ],
    [ "SAMD21E16L definitions", "group___s_a_m_d21_e16_l__definitions.html", "group___s_a_m_d21_e16_l__definitions" ],
    [ "SAMD21E17A definitions", "group___s_a_m_d21_e17_a__definitions.html", "group___s_a_m_d21_e17_a__definitions" ],
    [ "SAMD21E18A definitions", "group___s_a_m_d21_e18_a__definitions.html", "group___s_a_m_d21_e18_a__definitions" ],
    [ "SAMD21G15A definitions", "group___s_a_m_d21_g15_a__definitions.html", "group___s_a_m_d21_g15_a__definitions" ],
    [ "SAMD21G15B definitions", "group___s_a_m_d21_g15_b__definitions.html", "group___s_a_m_d21_g15_b__definitions" ],
    [ "SAMD21G15L definitions", "group___s_a_m_d21_g15_l__definitions.html", "group___s_a_m_d21_g15_l__definitions" ],
    [ "SAMD21G16A definitions", "group___s_a_m_d21_g16_a__definitions.html", "group___s_a_m_d21_g16_a__definitions" ],
    [ "SAMD21G16B definitions", "group___s_a_m_d21_g16_b__definitions.html", "group___s_a_m_d21_g16_b__definitions" ],
    [ "SAMD21G16L definitions", "group___s_a_m_d21_g16_l__definitions.html", "group___s_a_m_d21_g16_l__definitions" ],
    [ "SAMD21G17A definitions", "group___s_a_m_d21_g17_a__definitions.html", "group___s_a_m_d21_g17_a__definitions" ],
    [ "SAMD21G17AU definitions", "group___s_a_m_d21_g17_a_u__definitions.html", "group___s_a_m_d21_g17_a_u__definitions" ],
    [ "SAMD21G18A definitions", "group___s_a_m_d21_g18_a__definitions.html", "group___s_a_m_d21_g18_a__definitions" ],
    [ "SAMD21G18AU definitions", "group___s_a_m_d21_g18_a_u__definitions.html", "group___s_a_m_d21_g18_a_u__definitions" ],
    [ "SAMD21J15A definitions", "group___s_a_m_d21_j15_a__definitions.html", "group___s_a_m_d21_j15_a__definitions" ],
    [ "SAMD21J15B definitions", "group___s_a_m_d21_j15_b__definitions.html", "group___s_a_m_d21_j15_b__definitions" ],
    [ "SAMD21J16A definitions", "group___s_a_m_d21_j16_a__definitions.html", "group___s_a_m_d21_j16_a__definitions" ],
    [ "SAMD21J16B definitions", "group___s_a_m_d21_j16_b__definitions.html", "group___s_a_m_d21_j16_b__definitions" ],
    [ "SAMD21J17A definitions", "group___s_a_m_d21_j17_a__definitions.html", "group___s_a_m_d21_j17_a__definitions" ],
    [ "SAMD21J18A definitions", "group___s_a_m_d21_j18_a__definitions.html", "group___s_a_m_d21_j18_a__definitions" ]
];