var modules =
[
    [ "Generic board support", "group__group__common__boards.html", "group__group__common__boards" ],
    [ "Serial Interface (Serial)", "group__serial__group.html", null ],
    [ "Global interrupt management", "group__interrupt__group.html", "group__interrupt__group" ],
    [ "Atmel part identification macros", "group__part__macros__group.html", "group__part__macros__group" ],
    [ "AT25DFx SerialFlash Driver", "group__asfdoc__common2__at25dfx__group.html", "group__asfdoc__common2__at25dfx__group" ],
    [ "Busy-Wait Delay Routines", "group__group__common__services__delay.html", "group__group__common__services__delay" ],
    [ "AT30TSE75X Temperature Sensor", "group__asfdoc__sam0__at30tse75x__group.html", "group__asfdoc__sam0__at30tse75x__group" ],
    [ "SAM External Interrupt (EXTINT) Driver", "group__asfdoc__sam0__extint__group.html", "group__asfdoc__sam0__extint__group" ],
    [ "SAM Port (PORT) Driver", "group__asfdoc__sam0__port__group.html", "group__asfdoc__sam0__port__group" ],
    [ "SAM Serial Peripheral Interface (SERCOM SPI) Driver", "group__asfdoc__sam0__sercom__spi__group.html", "group__asfdoc__sam0__sercom__spi__group" ],
    [ "SAM Serial USART (SERCOM USART) Driver", "group__asfdoc__sam0__sercom__usart__group.html", "group__asfdoc__sam0__sercom__usart__group" ],
    [ "SAM System Clock Management (SYSTEM CLOCK) Driver", "group__asfdoc__sam0__system__clock__group.html", "group__asfdoc__sam0__system__clock__group" ],
    [ "SAM System Interrupt (SYSTEM INTERRUPT) Driver", "group__asfdoc__sam0__system__interrupt__group.html", "group__asfdoc__sam0__system__interrupt__group" ],
    [ "SAM System Pin Multiplexer (SYSTEM PINMUX) Driver", "group__asfdoc__sam0__system__pinmux__group.html", "group__asfdoc__sam0__system__pinmux__group" ],
    [ "SAM System (SYSTEM) Driver", "group__asfdoc__sam0__system__group.html", "group__asfdoc__sam0__system__group" ],
    [ "SAM Timer/Counter (TC) Driver", "group__asfdoc__sam0__tc__group.html", "group__asfdoc__sam0__tc__group" ],
    [ "SAMD21 Device Definitions", "group___s_a_m_d21__definitions.html", "group___s_a_m_d21__definitions" ],
    [ "Compiler abstraction layer and code utilities", "group__group__sam0__utils.html", "group__group__sam0__utils" ],
    [ "Standard I/O (stdio)", "group__group__common__utils__stdio.html", "group__group__common__utils__stdio" ],
    [ "Basic Math Functions", "group__group_math.html", null ],
    [ "Fast Math Functions", "group__group_fast_math.html", "group__group_fast_math" ],
    [ "Complex Math Functions", "group__group_cmplx_math.html", null ],
    [ "Filtering Functions", "group__group_filters.html", null ],
    [ "Matrix Functions", "group__group_matrix.html", null ],
    [ "Transform Functions", "group__group_transforms.html", null ],
    [ "Controller Functions", "group__group_controller.html", "group__group_controller" ],
    [ "Statistics Functions", "group__group_stats.html", null ],
    [ "Support Functions", "group__group_support.html", null ],
    [ "Interpolation Functions", "group__group_interpolation.html", "group__group_interpolation" ],
    [ "Examples", "group__group_examples.html", null ],
    [ "CMSIS Global Defines", "group___c_m_s_i_s__glob__defs.html", null ],
    [ "Defines and Type Definitions", "group___c_m_s_i_s__core__register.html", "group___c_m_s_i_s__core__register" ],
    [ "Functions and Instructions Reference", "group___c_m_s_i_s___core___function_interface.html", "group___c_m_s_i_s___core___function_interface" ],
    [ "CMSIS Core Instruction Interface", "group___c_m_s_i_s___core___instruction_interface.html", null ],
    [ "xCoRoutineCreate", "group__x_co_routine_create.html", null ],
    [ "vCoRoutineSchedule", "group__v_co_routine_schedule.html", null ],
    [ "crSTART", "group__cr_s_t_a_r_t.html", null ],
    [ "crDELAY", "group__cr_d_e_l_a_y.html", null ],
    [ "crQUEUE_SEND", "group__cr_q_u_e_u_e___s_e_n_d.html", null ],
    [ "crQUEUE_RECEIVE", "group__cr_q_u_e_u_e___r_e_c_e_i_v_e.html", null ],
    [ "crQUEUE_SEND_FROM_ISR", "group__cr_q_u_e_u_e___s_e_n_d___f_r_o_m___i_s_r.html", null ],
    [ "crQUEUE_RECEIVE_FROM_ISR", "group__cr_q_u_e_u_e___r_e_c_e_i_v_e___f_r_o_m___i_s_r.html", null ],
    [ "EventGroup", "group___event_group.html", "group___event_group" ],
    [ "xMessageBufferCreate", "group__x_message_buffer_create.html", null ],
    [ "xMessageBufferCreateStatic", "group__x_message_buffer_create_static.html", null ],
    [ "xMessageBufferSend", "group__x_message_buffer_send.html", null ],
    [ "xMessageBufferSendFromISR", "group__x_message_buffer_send_from_i_s_r.html", null ],
    [ "xMessageBufferReceive", "group__x_message_buffer_receive.html", null ],
    [ "xMessageBufferReceiveFromISR", "group__x_message_buffer_receive_from_i_s_r.html", null ],
    [ "xMessageBufferReset", "group__x_message_buffer_reset.html", null ],
    [ "xMessageBufferSpaceAvailable", "group__x_message_buffer_space_available.html", null ],
    [ "xMessageBufferSendCompletedFromISR", "group__x_message_buffer_send_completed_from_i_s_r.html", null ],
    [ "xMessageBufferReceiveCompletedFromISR", "group__x_message_buffer_receive_completed_from_i_s_r.html", null ],
    [ "xQueueCreate", "group__x_queue_create.html", null ],
    [ "xQueueCreateStatic", "group__x_queue_create_static.html", null ],
    [ "xQueueSend", "group__x_queue_send.html", null ],
    [ "xQueueOverwrite", "group__x_queue_overwrite.html", null ],
    [ "xQueuePeek", "group__x_queue_peek.html", null ],
    [ "xQueuePeekFromISR", "group__x_queue_peek_from_i_s_r.html", null ],
    [ "xQueueReceive", "group__x_queue_receive.html", null ],
    [ "uxQueueMessagesWaiting", "group__ux_queue_messages_waiting.html", null ],
    [ "vQueueDelete", "group__v_queue_delete.html", null ],
    [ "xQueueSendFromISR", "group__x_queue_send_from_i_s_r.html", null ],
    [ "xQueueOverwriteFromISR", "group__x_queue_overwrite_from_i_s_r.html", null ],
    [ "xQueueReceiveFromISR", "group__x_queue_receive_from_i_s_r.html", null ],
    [ "vSemaphoreCreateBinary", "group__v_semaphore_create_binary.html", null ],
    [ "xSemaphoreCreateBinary", "group__x_semaphore_create_binary.html", null ],
    [ "xSemaphoreCreateBinaryStatic", "group__x_semaphore_create_binary_static.html", null ],
    [ "xSemaphoreTake", "group__x_semaphore_take.html", null ],
    [ "xSemaphoreTakeRecursive", "group__x_semaphore_take_recursive.html", null ],
    [ "xSemaphoreGive", "group__x_semaphore_give.html", null ],
    [ "xSemaphoreGiveRecursive", "group__x_semaphore_give_recursive.html", null ],
    [ "xSemaphoreGiveFromISR", "group__x_semaphore_give_from_i_s_r.html", null ],
    [ "xSemaphoreCreateMutex", "group__x_semaphore_create_mutex.html", null ],
    [ "xSemaphoreCreateMutexStatic", "group__x_semaphore_create_mutex_static.html", null ],
    [ "xSemaphoreCreateRecursiveMutex", "group__x_semaphore_create_recursive_mutex.html", null ],
    [ "xSemaphoreCreateRecursiveMutexStatic", "group__x_semaphore_create_recursive_mutex_static.html", null ],
    [ "xSemaphoreCreateCounting", "group__x_semaphore_create_counting.html", null ],
    [ "xSemaphoreCreateCountingStatic", "group__x_semaphore_create_counting_static.html", null ],
    [ "vSemaphoreDelete", "group__v_semaphore_delete.html", null ],
    [ "xStreamBufferCreate", "group__x_stream_buffer_create.html", null ],
    [ "xStreamBufferCreateStatic", "group__x_stream_buffer_create_static.html", null ],
    [ "xStreamBufferSend", "group__x_stream_buffer_send.html", null ],
    [ "xStreamBufferSendFromISR", "group__x_stream_buffer_send_from_i_s_r.html", null ],
    [ "xStreamBufferReceive", "group__x_stream_buffer_receive.html", null ],
    [ "xStreamBufferReceiveFromISR", "group__x_stream_buffer_receive_from_i_s_r.html", null ],
    [ "vStreamBufferDelete", "group__v_stream_buffer_delete.html", null ],
    [ "xStreamBufferIsFull", "group__x_stream_buffer_is_full.html", null ],
    [ "xStreamBufferIsEmpty", "group__x_stream_buffer_is_empty.html", null ],
    [ "xStreamBufferReset", "group__x_stream_buffer_reset.html", null ],
    [ "xStreamBufferSpacesAvailable", "group__x_stream_buffer_spaces_available.html", null ],
    [ "xStreamBufferBytesAvailable", "group__x_stream_buffer_bytes_available.html", null ],
    [ "xStreamBufferSetTriggerLevel", "group__x_stream_buffer_set_trigger_level.html", null ],
    [ "xStreamBufferSendCompletedFromISR", "group__x_stream_buffer_send_completed_from_i_s_r.html", null ],
    [ "xStreamBufferReceiveCompletedFromISR", "group__x_stream_buffer_receive_completed_from_i_s_r.html", null ],
    [ "TaskHandle_t", "group___task_handle__t.html", null ],
    [ "taskYIELD", "group__task_y_i_e_l_d.html", null ],
    [ "taskENTER_CRITICAL", "group__task_e_n_t_e_r___c_r_i_t_i_c_a_l.html", null ],
    [ "taskEXIT_CRITICAL", "group__task_e_x_i_t___c_r_i_t_i_c_a_l.html", null ],
    [ "taskDISABLE_INTERRUPTS", "group__task_d_i_s_a_b_l_e___i_n_t_e_r_r_u_p_t_s.html", null ],
    [ "taskENABLE_INTERRUPTS", "group__task_e_n_a_b_l_e___i_n_t_e_r_r_u_p_t_s.html", null ],
    [ "xTaskCreate", "group__x_task_create.html", null ],
    [ "xTaskCreateStatic", "group__x_task_create_static.html", null ],
    [ "xTaskCreateRestricted", "group__x_task_create_restricted.html", null ],
    [ "xTaskCreateRestrictedStatic", "group__x_task_create_restricted_static.html", null ],
    [ "vTaskDelete", "group__v_task_delete.html", null ],
    [ "vTaskDelay", "group__v_task_delay.html", null ],
    [ "vTaskDelayUntil", "group__v_task_delay_until.html", null ],
    [ "xTaskAbortDelay", "group__x_task_abort_delay.html", null ],
    [ "uxTaskPriorityGet", "group__ux_task_priority_get.html", null ],
    [ "vTaskGetInfo", "group__v_task_get_info.html", null ],
    [ "vTaskPrioritySet", "group__v_task_priority_set.html", null ],
    [ "vTaskSuspend", "group__v_task_suspend.html", null ],
    [ "vTaskResume", "group__v_task_resume.html", null ],
    [ "vTaskResumeFromISR", "group__v_task_resume_from_i_s_r.html", null ],
    [ "vTaskStartScheduler", "group__v_task_start_scheduler.html", null ],
    [ "vTaskEndScheduler", "group__v_task_end_scheduler.html", null ],
    [ "vTaskSuspendAll", "group__v_task_suspend_all.html", null ],
    [ "xTaskResumeAll", "group__x_task_resume_all.html", null ],
    [ "xTaskGetTickCount", "group__x_task_get_tick_count.html", null ],
    [ "xTaskGetTickCountFromISR", "group__x_task_get_tick_count_from_i_s_r.html", null ],
    [ "uxTaskGetNumberOfTasks", "group__ux_task_get_number_of_tasks.html", null ],
    [ "pcTaskGetName", "group__pc_task_get_name.html", null ],
    [ "pcTaskGetHandle", "group__pc_task_get_handle.html", null ],
    [ "vTaskList", "group__v_task_list.html", null ],
    [ "vTaskGetRunTimeStats", "group__v_task_get_run_time_stats.html", null ],
    [ "xTaskNotify", "group__x_task_notify.html", null ],
    [ "xTaskNotifyWait", "group__x_task_notify_wait.html", null ],
    [ "xTaskNotifyGive", "group__x_task_notify_give.html", null ],
    [ "ulTaskNotifyTake", "group__ul_task_notify_take.html", null ],
    [ "xTaskNotifyStateClear", "group__x_task_notify_state_clear.html", null ],
    [ "SIO2HOST - UART", "group__group__sio2host__uart.html", "group__group__sio2host__uart" ],
    [ "BLE Manager", "group__ble__manager.html", "group__ble__manager" ],
    [ "GAP APIs", "group__gap__group.html", "group__gap__group" ],
    [ "GATT Client APIs", "group__gatt__client__group.html", "group__gatt__client__group" ],
    [ "GATT Server APIs", "group__gatt__server__group.html", "group__gatt__server__group" ],
    [ "L2CAP APIs", "group__l2cap__group.html", "group__l2cap__group" ],
    [ "HTPT APIs", "group__htpt__group.html", "group__htpt__group" ],
    [ "Misc APIs", "group__misc__group.html", "group__misc__group" ],
    [ "Error codes", "group__error__codes__group.html", "group__error__codes__group" ],
    [ "Direct test Mode APIs (DTM)", "group__dtm__group.html", "group__dtm__group" ],
    [ "Calibration APIs", "group__calib__group.html", "group__calib__group" ],
    [ "MACROs", "group__dbg__logs__group__macros.html", "group__dbg__logs__group__macros" ],
    [ "Functions", "group__dbg__logs__group__functions.html", "group__dbg__logs__group__functions" ],
    [ "Examples", "group__dbg__logs__group__examples.html", null ],
    [ "serial First-In-First-Out Buffer (FIFO)", "group__fifo__group.html", "group__fifo__group" ],
    [ "Asfdoc_sam0_sercom_i2c_group", "group__asfdoc__sam0__sercom__i2c__group.html", "group__asfdoc__sam0__sercom__i2c__group" ],
    [ "Analog Comparators", "group___s_a_m_d21___a_c.html", "group___s_a_m_d21___a_c" ],
    [ "Analog Digital Converter", "group___s_a_m_d21___a_d_c.html", "group___s_a_m_d21___a_d_c" ],
    [ "Digital Analog Converter", "group___s_a_m_d21___d_a_c.html", "group___s_a_m_d21___d_a_c" ],
    [ "Direct Memory Access Controller", "group___s_a_m_d21___d_m_a_c.html", "group___s_a_m_d21___d_m_a_c" ],
    [ "Device Service Unit", "group___s_a_m_d21___d_s_u.html", "group___s_a_m_d21___d_s_u" ],
    [ "External Interrupt Controller", "group___s_a_m_d21___e_i_c.html", "group___s_a_m_d21___e_i_c" ],
    [ "Event System Interface", "group___s_a_m_d21___e_v_s_y_s.html", "group___s_a_m_d21___e_v_s_y_s" ],
    [ "Generic Clock Generator", "group___s_a_m_d21___g_c_l_k.html", "group___s_a_m_d21___g_c_l_k" ],
    [ "HSB Matrix", "group___s_a_m_d21___h_m_a_t_r_i_x_b.html", "group___s_a_m_d21___h_m_a_t_r_i_x_b" ],
    [ "Inter-IC Sound Interface", "group___s_a_m_d21___i2_s.html", "group___s_a_m_d21___i2_s" ],
    [ "Cortex-M0+ Micro-Trace Buffer", "group___s_a_m_d21___m_t_b.html", "group___s_a_m_d21___m_t_b" ],
    [ "Non-Volatile Memory Controller", "group___s_a_m_d21___n_v_m_c_t_r_l.html", "group___s_a_m_d21___n_v_m_c_t_r_l" ],
    [ "Peripheral Software API", "group__fuses__api.html", "group__fuses__api" ],
    [ "Peripheral Access Controller", "group___s_a_m_d21___p_a_c.html", "group___s_a_m_d21___p_a_c" ],
    [ "Power Manager", "group___s_a_m_d21___p_m.html", "group___s_a_m_d21___p_m" ],
    [ "Port Module", "group___s_a_m_d21___p_o_r_t.html", "group___s_a_m_d21___p_o_r_t" ],
    [ "Real-Time Counter", "group___s_a_m_d21___r_t_c.html", "group___s_a_m_d21___r_t_c" ],
    [ "Serial Communication Interface", "group___s_a_m_d21___s_e_r_c_o_m.html", "group___s_a_m_d21___s_e_r_c_o_m" ],
    [ "System Control", "group___s_a_m_d21___s_y_s_c_t_r_l.html", "group___s_a_m_d21___s_y_s_c_t_r_l" ],
    [ "Basic Timer Counter", "group___s_a_m_d21___t_c.html", "group___s_a_m_d21___t_c" ],
    [ "Timer Counter Control", "group___s_a_m_d21___t_c_c.html", "group___s_a_m_d21___t_c_c" ],
    [ "Universal Serial Bus", "group___s_a_m_d21___u_s_b.html", "group___s_a_m_d21___u_s_b" ],
    [ "Watchdog Timer", "group___s_a_m_d21___w_d_t.html", "group___s_a_m_d21___w_d_t" ]
];